insert into productcategory values (1, 1, 'Bakery'); 
insert into productcategory values (2, 2, 'Biscuits & crackers'); 
insert into productcategory values (3, 3, 'Cereal & flakes'); 
insert into productcategory values (4, 4, 'Desserts'); 
insert into productcategory values (5, 5, 'Drinks'); 
insert into productcategory values (6, 6, 'Dairy & youghurts'); 
insert into productcategory values (7, 7, 'Fish & seafood'); 
insert into productcategory values (8, 8, 'Frozen & prepared foods'); 
insert into productcategory values (9, 9, 'Fruit preserves & jams'); 
insert into productcategory values (10, 10, 'Meat & poultry'); 
insert into productcategory values (11, 11, 'Pasta, noodles & rice'); 
insert into productcategory values (12, 12, 'Sauces & condiments'); 
insert into productcategory values (13, 13, 'Snacks & treats'); 
insert into productcategory values (14, 14, 'Spices & seasoning'); 
insert into productcategory values (15, 15, 'Vegetable preserves & relishes'); 
insert into productcategory values (16, 16, 'MISC'); 
