insert into productcategory values (1, 1, 'Bröd'); 
insert into productcategory values (2, 2, 'Kex och kakor'); 
insert into productcategory values (3, 3, 'Spannmål och flingor'); 
insert into productcategory values (4, 4, 'Efterätter'); 
insert into productcategory values (5, 5, 'Drycker'); 
insert into productcategory values (6, 6, 'Mjölkprodukter & youghurt'); 
insert into productcategory values (7, 7, 'Fisk och skaldjur'); 
insert into productcategory values (8, 8, 'Fryst & färdigmat'); 
insert into productcategory values (9, 9, 'Fruktkonserver och sylt'); 
insert into productcategory values (10, 10, 'Kött & fågel'); 
insert into productcategory values (11, 11, 'Pasta, nudlar och ris'); 
insert into productcategory values (12, 12, 'Såser och smaktillsatser'); 
insert into productcategory values (13, 13, 'Snacks och godis'); 
insert into productcategory values (14, 14, 'Kryddor'); 
insert into productcategory values (15, 15, 'Grönsakskonserver'); 
insert into productcategory values (16, 16, 'Övrigt'); 
