update productcategory set name = 'Bröd' where id = 1;
update productcategory set name = 'Kex och kakor '  where id = 2;
update productcategory set name = 'Spannmål och flingor'  where id = 3;
update productcategory set name = 'Efterätter' where id = 4;
update productcategory set name = 'Drycker' where id = 5;
update productcategory set name = 'Mjölkprodukter & youghurt' where id = 6;
update productcategory set name = 'Fisk och skaldjur' where id = 7;
update productcategory set name = 'Fryst & färdigmat' where id = 8;
update productcategory set name = 'Fruktkonserver och sylt' where id = 9;
update productcategory set name = 'Kött & fågel' where id = 10;
update productcategory set name = 'Pasta, nudlar och ris' where id = 11;
update productcategory set name = 'Såser och smaktillsatser' where id = 12;
update productcategory set name = 'Snacks och godis' where id = 13;
update productcategory set name = 'Kryddor' where id = 14;
update productcategory set name = 'Grönsakskonserver' where id = 15;
update productcategory set name = 'Övrigt' where id = 16;
