insert into productcategory values (1, 1, 'Bageri'); 
insert into productcategory values (2, 2, 'Kex och kex'); 
insert into productcategory values (3, 3, 'Spannmål och flingor'); 
insert into productcategory values (4, 4, 'Desserter'); 
insert into productcategory values (5, 5, 'Drycker'); 
insert into productcategory values (6, 6, 'Mjölkprodukter & youghurt'); 
insert into productcategory values (7, 7, 'Fisk och skaldjur'); 
insert into productcategory values (8, 8, 'Frysta & färdigmat'); 
insert into productcategory values (9, 9, 'Frukt konserver och sylt'); 
insert into productcategory values (10, 10, 'Kött & fågel'); 
insert into productcategory values (11, 11, 'Pasta, nudlar och ris'); 
insert into productcategory values (12, 12, 'Såser och smaktillsatser'); 
insert into productcategory values (13, 13, 'Snacks och godis'); 
insert into productcategory values (14, 14, 'Kryddor och kryddor'); 
insert into productcategory values (15, 15, 'Grönsakskonserver & relishes'); 
insert into productcategory values (16, 16, 'MISC'); 
